# (APPENDIX) Appendix {-} 

# Preguntas más frecuentes sobre la herramienta FishPath

##### ¿Cómo envío comentarios sobre el contenido o la experiencia del usuario? {#faq-feedback}

FishPath se beneficia de la experiencia y sugerencias de la comunidad global de los usuarios, que son alentados a ingresar sus sugerencias sobre la herramienta FishPath, para ayudarnos a mejorar. Hay dos maneras en las que puede ingresar sus sugerencias:

1.	El botón “Ingresar sugerencias” en el tablero de la herramienta FishPath. Se le sugiere al usuario a categorizar sus sugerencias como “Relacionado al contenido” o “Problemas con el software”.
2.	Enviar un correo electrónico a la dirección support@fishpath.org 

##### ¿Cómo se actualiza el contenido de la herramienta FishPath (preguntas, opciones, advertencias, etc.)? ¿Y con qué frecuencia? {#faq-content-updates}

El equipo de FishPath está compuesto por científicos pesqueros y expertos en la gestión de pesquerías que se mantienen actualizados en el ámbito dinámico de la investigación pesquera. La herramienta se mantiene con el objetivo de estar lo más actualizada posible con las prácticas de ordenación pesquera, la ciencia y la literatura. También nos esforzamos por corregir cualquier error encontrado en la herramienta lo más rápido posible. Para ello, se pueden realizar actualizaciones de contenido en cualquier momento.

Las sugerencias de los usuarios con respecto al contenido también son muy apreciadas y alentadas. Reconocemos que las pesquerías ocurren en una amplia variedad de contextos y nuestro pequeño equipo no puede conocer todos los escenarios y advertencias posibles. Cualquier comentario recibirá una revisión completa y se incorporará a la herramienta según sea necesario.

Cada vez que un usuario inicia sesión, la herramienta utilizará la versión más actualizada del contenido de la herramienta. No es necesario realizar ninguna acción para recibir las actualizaciones, incluso si el cuestionario ya está completado. Si se ha agregado una nueva pregunta después de que un usuario haya completado el cuestionario, aparecerá un mensaje para responder esa pregunta antes de regresar a la pantalla de resultados.

##### ¿Cómo puede mantenerse actualizado sobre los cambios en el contenido o el cuestionario de la herramienta FishPath? {#faq-stay-updated}

En el boletín semestral se documenta un breve resumen de los cambios importantes.

En [el registro de cambios](https://github.com/FishPath/FishPath-Tool-User-Guide/blob/master/Major%20Content%20Updates.md) se documenta una lista actualizada de todos los cambios de contenido. Esta lista contiene una descripción general de los cambios importantes, como preguntas y opciones nuevas o editadas. [Aquí se encuentra](https://docs.google.com/spreadsheets/d/1HPlUvI6XuvXtYdFk5bpOsG4JR1fdM0D58KO5mBs0fyE/edit?usp=sharing) una hoja de cálculo detallada de todos los criterios y cambios de advertencia. Le permite filtrar y ordenar por opciones o preguntas específicas.

##### ¿Las respuestas a las preguntas nuevas también son actualizadas en “las pesquerías copiadas”? {#faq-copy-fisheries}

Una vez que una pesquería es copiada, los cambios a la pesquería original o copiada no tendrán efectos uno sobre el otro.

##### ¿La herramienta FishPath necesita Internet para funcionar? {#faq-internet}

La herramienta FishPath requiere una conexión a Internet para cargarse y funcionar correctamente. Sin embargo, la herramienta ha sido diseñada para manejar conexiones a Internet intermitentes. Una vez que haya iniciado sesión, la herramienta puede funcionar parcialmente sin Internet. Si la señal se corta o se retrasa, la herramienta guardará las respuestas a las preguntas o los cambios realizados mientras está “fuera de línea” hasta que pueda volver a conectarse con el servidor y guardar los cambios. La [“barra de herramientas del estado de guardado”][La barra de herramientas del estado de guardado] en la parte inferior de la pantalla le permite al usuario saber si algún cambio no se ha podido guardar en el servidor. Cerrar la ventana o navegar fuera de la herramienta cuando hay cambios no guardados hará que esos cambios se pierdan.

##### ¿Por qué parece cambiar el número de preguntas de cada sección? {#faq-question-numbering}

Muchas de las preguntas del cuestionario son relevantes para múltiples secciones. Una vez que responda a una pregunta que afecta a varias secciones, la herramienta no repetirá esa pregunta al completar el cuestionario para otra sección. Por ejemplo, antes de comenzar el cuestionario para cualquier sección, hay 41 preguntas en la sección de colecta de datos, 50 preguntas en evaluación y 44 en medidas de manejo. Un usuario comienza el cuestionario con la sección de recopilación de datos. 6 de esas preguntas también se aplican a la evaluación y 14 también a las medidas de manejo. Si después el usuario responde la sección de evaluación, en lugar de que se le hagan las 50 preguntas, solo se le harán 44, ya que 6 de las preguntas ya han sido respondidas al completar el cuestionario de colecta de datos. Asimismo, si el usuario responde a continuación a la sección medidas de manejo, solo se le harían 30 preguntas.

